services:
  - type: web
    name: speakenglish
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node start-server.js
    envVars:
      - key: NODE_ENV
        value: production
